SONARCLOUD - STOP pipeline on vulnerabilities found

diff --git a/.github/workflows/PipelinePS.yml b/.github/workflows/PipelinePS.yml
--- a/.github/workflows/PipelinePS.yml
+++ b/.github/workflows/PipelinePS.yml
@@ -49,6 +49,15 @@ jobs:
             -Dsonar.exclusions=**/node_modules/**,**/android/**,**/ios/**
             -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
 
+      # Check SonarCloud Quality Gate
+      - name: Check SonarCloud Quality Gate
+        run: |
+          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECTKEY }}" | jq -r '.projectStatus.status')
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed. Aborting pipeline."
+            exit 1
+          fi
+
   SCA-SNYK:
     needs: SAST-SonarCloud
     runs-on: ubuntu-latest
